MICRO_SERVICE_ID=1
mode=1
router=3

client_id=10001
secret_key=RCLbm2xqh1An-AhO0MfiDqB-yi9xO3bB-PdG510-VR1JV-20938
access_token_key=8m#ApFYB4Q7uyew45EJNWntSaJWdGqDM
scope=all
scopenumber=9933

APP_ID=10001
APP_SECRET=EEEE
APP_SECRET_KEY=TEEE
ACCESS_TOKEN_SECRET=XXXSSS
JWT_SECRET=EEEEE

UPLOAD_DIR=./upload/user
TIMEEXPIRE = 31556926
TIMEEXPIRE_TOKEN =1h
TIMEEXPIRE_TOKEN_resetPassword1 =3600
TIMEEXPIRE_TOKEN_resetPassword =3600s
TIMEEXPIRE_TOKEN_activecode =1y
TIMEEXPIRE_DAY =1d
TIMEEXPIRE_SEC =120s
TIMEEXPIRE_HOUR =1h
TIMEEXPIRE_MONTH=1m
TIMEEXPIRE_YEAR=1y

TIMEEXPIRE0 = 2592000
TIMEEXPIRE0_ADY = 30
TIMEEXPIRE1 = 604800
TIMEEXPIRE1_ADY = 7
TIMEEXPIRE2 = 31556926
TIMEEXPIRE2_ADY = 1

assets=./public/assets
css=./public/assets/css
js=./public/assets/js
data=./public/assets/data
fonts=./public/assets/fonts
html=./public/assets/html
fonts=./public/assets/fonts
image=./public/assets/image
img=./public/assets/img 

email_host=smtp.gamil.com
email_port=587
email_host_user=tppytcas@gamil.com
email_host_password=tppytcas@2021

user=kongnakorn@gmail.com
pass=K@5371@#
resetpassoff=911

path_entities1=src
path_entities2=dist
path_entities=dist